services:
  postgres:
    image: postgres:15
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: languagebox
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d languagebox"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
  frontend:
    build: ./frontend
    container_name: language-box-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend2
  backend0:
    build: ./backend
    container_name: language-box-backend-0
    ports:
      - "8000:8000"
    environment:
      - BACKEND_INDEX=0
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=languagebox
    depends_on:
      - postgres
  backend1:
    build: ./backend
    container_name: language-box-backend-1
    ports:
      - "8001:8000"
    environment:
      - BACKEND_INDEX=1
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=languagebox
    depends_on:
      - backend0
  backend2:
    build: ./backend
    container_name: language-box-backend-2
    ports:
      - "8002:8000"
    environment:
      - BACKEND_INDEX=2
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=languagebox
    depends_on:
      - backend1

volumes:
  postgres_data:
  