services:
  postgres:
    image: postgres:15
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: languagebox
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d languagebox"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
  frontend1:
    build: ./frontend
    container_name: language-box-frontend-1
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - APP_INDEX=1
  frontend2:
    build: ./frontend
    container_name: language-box-frontend-2
    ports:
      - "3001:80"
    depends_on:
      - backend
    environment:
      - APP_INDEX=2
  frontend3:
    build: ./frontend
    container_name: language-box-frontend-3
    ports:
      - "3002:80"
    depends_on:
      - backend
    environment:
      - APP_INDEX=3
  backend:
    build: ./backend
    container_name: language-box-backend
    ports:
      - "8000:8000"
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=languagebox
    depends_on:
      - postgres

volumes:
  postgres_data:
  